[package]
name = "tg-rcore-tutorial-easy-fs-T1L4"
description = "ch6 T1L4. A simple filesystem implementation for rCore tutorial OS."
version = "0.0.1-preview.1"
edition = "2024"
authors = ["Yifan Wu <shinbokuow@163.com>"]
repository = "https://github.com/os-biglab/tg-rcore-tutorial-easy-fs-T1L4"
homepage = "https://github.com/os-biglab/tg-rcore-tutorial-easy-fs-T1L4/tree/test"
documentation = "https://github.com/os-biglab/tg-rcore-tutorial-easy-fs-T1L4/tree/test/docs"
license = "GPL-3.0"
readme = "README.md"
keywords = ["rcore", "filesystem", "no-std", "riscv"]
categories = ["no-std", "embedded", "filesystem"]

[dependencies]
spin = "0.9"
bitflags = "1.2"
